# Generated by Django 3.2.6 on 2021-08-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
