# Generated by Django 3.2.6 on 2021-08-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210813_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='release_date',
            field=models.DateField(),
        ),
    ]
