# Generated by Django 3.2.6 on 2021-08-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogpost_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
