# Generated by Django 3.2.6 on 2021-08-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogpost_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='release_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
