# Generated by Django 3.2.6 on 2021-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210813_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='contenido del post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tittle',
            field=models.CharField(max_length=200, verbose_name='titulo'),
        ),
    ]
